# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: mystiq
open_collective: mystiq
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: #MystiQ Video Converter
liberapay: MystiQ
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: ["http://paypal.me/webmisolutions"]
