######################################################################
# Automatically generated by qmake (2.01a) ?? 7? 2 21:43:55 2013
######################################################################

CONFIG += qtestlib
TARGET = testversioncompare
TEMPLATE = app

# Directories

HEADERS += \
    testversioncompare.h

SOURCES += \
    testversioncompare.cpp \
    ../../services/versioncompare.cpp
