######################################################################
# Automatically generated by qmake (2.01a) ?? 7? 19 11:46:16 2013
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = testupdateinfoparser

# Input
HEADERS += testupdateinfoparser.h ../../services/updateinfoparser.h \
           ../../services/xmllookuptable.cpp
SOURCES += testupdateinfoparser.cpp ../../services/updateinfoparser.cpp \
           ../../services/xmllookuptable.cpp
